LoveRoom/LoveRoom/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from apps.house import views

import os
import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "LoveRoom.settings")
django.setup()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^house/',include('apps.house.urls',namespace='house')),
    url(r'^uc/',include('apps.Uc.urls', namespace='uc')),
    url(r'^apis/', include('apps.apis.urls', namespace="apis")),
    url(r'^show/',include('apps.show.urls', namespace="show")),
    url(r'^owner/',include('apps.owner.urls', namespace="owner")),
    url(r'^blog/',include('apps.blog.urls', namespace="blog")),
    url(r'^pay/',include('apps.alipay.urls')),
    url(r'^$',views.index)
]


# meida 处理
from . import settings
if settings.DEBUG:
    from django.views.static import serve
    urlpatterns += [
        url(r'^media/(?P<path>.*)$',  serve, {"document_root": settings.MEDIA_ROOT}),
    ]

LoveRoom/apps/Uc/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^register/$',views.Register.as_view(), name='register'),
    url(r'^phonelogin/$',views.PhoneLogin.as_view(),name='phonelogin'),
    url(r'^pwlogin/$',views.PwLogin.as_view(),name='pwlogin'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^change_passwd/$',views.ChangePasswd.as_view(),name="change_passwd"),
    url(r'^profile/$',views.ProfileView.as_view(),name="profile"),
    url(r'^collect/$',views.Collect.as_view(),name="collect"),
    url(r'^order/$',views.Order.as_view(),name="order"),
    url(r'^myhouse/$',views.Myhouse.as_view(),name="myhouse"),

]

LoveRoom/apps/Uc/models.py
from django.db import models
# Create your models here.
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    realname = models.CharField(max_length=8, verbose_name="真实姓名")
    mobile = models.CharField(max_length=11, verbose_name="手机号")
    qq = models.CharField(max_length=11, verbose_name="QQ号")
    wechat = models.CharField(max_length=15,verbose_name="微信号")
    weibo = models.CharField(max_length=15,verbose_name="微博号")
    avator_sor = models.ImageField(upload_to="avator/", default="avator/default.jpg", verbose_name="头像")
    ID_num = models.CharField(max_length=18,verbose_name="身份证号")
    # 0表示男，1表示女，2表示保密
    SEX_CHOICES = (
        (0, '男'),
        (1, '女'),
        (None, '保密'),  # 把------去掉
    )
    sex = models.IntegerField(choices=SEX_CHOICES, null=True, blank=True, default=None, verbose_name="性别")
    introduce = models.TextField(verbose_name="自我介绍")
    nickname = models.CharField(max_length=24, verbose_name="昵称")
    is_owner = models.BooleanField(verbose_name="是否是房东",default=False)

    def __str__(self):
        return self.username


class Owner(models.Model):
    user = models.ForeignKey(User,verbose_name="用户")

LoveRoom/apps/Uc/forms.py
"""
file：forms.py
author：陈先生
date：2019/8/417:54
blog:https://chenpb-lu.github.io
"""
from django import forms
from django.forms import widgets
from django.core.exceptions import ValidationError
from .models import User
from django.contrib.auth.hashers import check_password as auth_check_password

class RegisterForm(forms.ModelForm):
    mobile_captcha = forms.CharField(label="验证码", widget=widgets.TextInput(
        attrs={'type':"text", 'class':"kapkey" ,'maxlength':"6" ,'placeholder':"验证码",'style':{'backgroud':'white !important'} }))
    password1 = forms.CharField(widget=widgets.TextInput(attrs={'type':"text", 'class':"password1", 'maxlength':"16", 'autocomplete':"off", 'placeholder':"密码"}))
    class Meta:
        model = User
        fields = ['mobile', 'password']
        widgets = {
            'mobile': widgets.TextInput(attrs={'type':"text", 'class':"phone", 'maxlength':"11", 'placeholder':"手机号码" ,'style':{'backgroud':'white !important'}}),
            'password': widgets.PasswordInput(attrs={'type':"password", 'class':"password", 'maxlength':"16", 'autocomplete':"off", 'placeholder':"密码"}),
        }

    def clean_mobile(self):
        ret = User.objects.filter(mobile=self.cleaned_data.get("mobile"))
        if not ret:
            return self.cleaned_data.get("mobile")
        else:
            raise ValidationError("手机号已绑定")

    def clean_password(self):
        data = self.cleaned_data.get("password")
        if not data.isdigit():
            return self.cleaned_data.get("password")
        else:
            raise ValidationError("密码不能全是数字")


class PhoneLoginForm(forms.Form):
    # 因为是登录功能，所以不适合ModelForm。
    # ModelForm对于unique字段会检查是否已经存在，如果存在，is_valid结果会为False


    mobile_captcha_login = forms.CharField(label="验证码", widget=widgets.TextInput(
        attrs={'type':"text", 'class':"kapkey_login" ,'maxlength':"6" ,'placeholder':"验证码",'style': {'backgroud': 'white !important'}
               }))
    mobile_login = forms.CharField(label="手机",widget=widgets.TextInput(
        attrs={"type": "text", "class": "phone_login", "maxlength":"11", "placeholder":"手机号码",
                       'style': {'backgroud': 'white !important'}}
    ))


    def clean_phone(self):

        ret = User.objects.filter(mobile=self.cleaned_data.get("mobile_login"))
        print(ret)
        if ret:
            return self.cleaned_data.get("mobile_login")
        else:
            raise ValidationError("用户名或密码不正确")


class PwLoginForm(forms.Form):
    # 因为是登录功能，所以不适合ModelForm。
    # ModelForm对于unique字段会检查是否已经存在，如果存在，is_valid结果会为False

    password1_login = forms.CharField(widget=widgets.TextInput(
        attrs={'type': "text", 'class': "password1N", 'maxlength': "16", 'autocomplete': "off", 'placeholder': "密码"}))

    password_login = forms.CharField(widget=widgets.TextInput(
        attrs={'type': "password", 'class': "passwordN", 'maxlength': "16", 'autocomplete': "off", 'placeholder': "密码"}))

    mobile_pwlogin = forms.CharField(label="手机",widget=widgets.TextInput(
        attrs={"type": "text", "class": "username", "maxlength":"11", "placeholder":"手机号码",
                       'style': {'backgroud': 'white !important'}}
    ))


    def check_password(self):
        print('check password')
        mobile = self.cleaned_data['mobile_pwlogin']
        password = self.cleaned_data['password_login']
        try:
            user = User.objects.get(mobile=mobile)
            print(user.username)
            return user, auth_check_password(password, user.password)
        except:
            return None, False

LoveRoom/apps/Uc/views.py
from django.shortcuts import render,redirect, reverse
from django.views.generic import View
import logging
from django.http import JsonResponse
from django.contrib import auth
from django.contrib.auth.hashers import make_password
from .models import User
from apps.house.models import HouseInfo
from .forms import RegisterForm,PhoneLoginForm,PwLoginForm
from django.core.paginator import Paginator,EmptyPage, PageNotAnInteger
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
logger = logging.getLogger('account')
from django.contrib.auth.hashers import check_password as auth_check_password

class LoginRequiredMixin(object):
    """
    登陆限定，并指定登陆url
    """
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
        return login_required(view, login_url='/')

# Create your views here.
class Register(View):
    def get(self, request):
        form = RegisterForm()
        return render(request, "house/index.html")

    # Ajax提交表单
    def post(self, request):
        from django.core.cache import cache
        ret = {"status": 400, "msg": "调用方式错误"}
        if request.is_ajax():
            print(request.POST)
            form = RegisterForm(request.POST)
            if form.is_valid():
                password = form.cleaned_data["password"]
                password1 = form.cleaned_data["password1"]
                print(f"{password}--{password1}")
                mobile = form.cleaned_data["mobile"]
                username = "手机用户" + mobile
                mobile_captcha = form.cleaned_data["mobile_captcha"]
                print(mobile_captcha)
                # print(username)
                mobile_captcha_reids = '123456'
                # mobile_captcha_reids = cache.get(mobile)
                if mobile_captcha == mobile_captcha_reids:
                    print("通过验证")
                    user = User.objects.create(username=username,mobile=mobile, password=make_password(password))
                    user.save()
                    ret['status'] = 200
                    ret['msg'] = "注册成功"
                    logger.debug(f"新用户{user.username}注册成功！")

                    user = auth.authenticate(username=username, password=password)
                    if user is not None and user.is_active:
                        auth.login(request, user)
                        logger.debug(f"新用户{user.username}登录成功")
                    else:
                        logger.error(f"新用户{username}登录失败")
                else:
                    # 验证码错误
                    ret['status'] = 401
                    ret['msg'] = "验证码错误或过期"
            else:
                ret['status'] = 402
                ret['msg'] = "该手机号已注册"
        logger.debug(f"用户注册结果：{ret}")
        return JsonResponse(ret)

class PhoneLogin(View):
    def get(self, request):
        # 如果已登录，则直接跳转到index页面
        # request.user 表示的是当前登录的用户对象,没有登录 `匿名用户`
        phone_login_form = PhoneLoginForm()
        if request.user.is_authenticated:
            return redirect(reverse('house:index'))
        # 设置下一跳转地址
        request.session["next"] =  request.GET.get('next',reverse('house:index'))
        return render(request, "house/index.html")

        # Form表单直接提交
    def post(self, request):
        # 表单数据绑定
        ret = {"status": 400, "msg": "调用方式错误"}
        phone_login_form = PhoneLoginForm(request.POST)
        if phone_login_form.is_valid():
            mobile = phone_login_form.cleaned_data["mobile_login"]
            mobile_captcha = phone_login_form.cleaned_data["mobile_captcha_login"]
            mobile_captcha_reids = '123456'
            # mobile_captcha_reids = cache.get(mobile)
            logger.debug(f"登录提交验证码:{mobile_captcha}-{mobile_captcha_reids}")
            # 验证码一致
            if mobile_captcha == mobile_captcha_reids:
                user = User.objects.get(mobile=mobile)
                # user = auth.authenticate(username=username, password=password)
                if user is not None and user.is_active :
                    auth.login(request, user)
                    ret['status'] = 200
                    ret['msg'] = "登录成功"
                    logger.info(f"{user.username}登录成功")
                else:
                    ret['status'] = 401
                    ret['msg'] = "该手机号未注册"
                    logger.error(f"{mobile}登录失败, 手机号未注册")
            else:
                ret['status'] = 402
                ret['msg'] = "验证码错误"
                logger.error(f"验证码错误")
        else:
            msg = "表单数据不完整"
            logger.error(phone_login_form.errors)
            logger.error(msg)
        return JsonResponse(ret)

class PwLogin(View):
    def get(self, request):
        # 如果已登录，则直接跳转到index页面
        # request.user 表示的是当前登录的用户对象,没有登录 `匿名用户`
        phone_login_form = PwLoginForm()
        if request.user.is_authenticated:
            return redirect(reverse('house:index'))
        # 设置下一跳转地址
        request.session["next"] =  request.GET.get('next',reverse('house:index'))
        return render(request, "house/index.html")

        # Form表单直接提交
    def post(self, request):
        # 表单数据绑定
        ret = {"status": 400, "msg": "调用方式错误"}
        pw_login_form = PwLoginForm(request.POST)
        if pw_login_form.is_valid():
            mobile = pw_login_form.cleaned_data["mobile_pwlogin"]
            password = pw_login_form.cleaned_data['password_login']
            password1 = pw_login_form.cleaned_data['password1_login']

            logger.debug(f"登录提交密码:{password}-{password1}")
            user, flag = pw_login_form.check_password()
            print(user.username)
            if user is not None and user.is_active and flag:
                if user is not None and user.is_active :
                    auth.login(request, user)
                    ret['status'] = 200
                    ret['msg'] = "登录成功"
                    logger.info(f"{user.username}登录成功")
            else:
                ret['status'] = 401
                ret['msg'] = "手机号或密码错误"
                logger.error(f"手机号或密码错误")
        else:
            msg = "表单数据不完整"
            logger.error(pw_login_form.errors)
            logger.error(msg)
        return JsonResponse(ret)


def logout(request):
    logger.info(f"{request.user.username}注销成功")
    auth.logout(request)
    return redirect(reverse("house:index"))


class ChangePasswd(LoginRequiredMixin,View):
    def get(self,request):
        return render(request,'uc/uc_change_passwd.html')
    def post(self,request):
        ret = {"status": 400, "msg": "调用方式错误"}
        oldpassword = request.POST.get("oldpassword")
        newpasswd1 = request.POST.get("newpassword1")
        if auth_check_password(oldpassword, request.user.password):
            request.user.password=make_password(newpasswd1)
            logger.info(f"{request.user.username}注销成功")
            logger.info(f"{request.user.username}修改密码成功")
            request.user.save()
            return render(request,'house/index.html',{"msg":"修改密码成功，请重新登录"})

        else:
            ret ={"status": 300, "msg": "旧密码错误"}
            return render(request,"uc/uc_change_passwd.html",{"msg":"旧密码错误"})




class ProfileView(LoginRequiredMixin,View):
    def get(self,request):
        return render(request, "uc/uc_profile.html")

    def post(self, request):
        ret_info = {"code": 200, "msg": "修改成功"}
        try:
            if request.POST.get("email"):
                request.user.email = request.POST.get("email")
            if request.POST.get("mobile"):
                print('change mobile')
                request.user.mobile = request.POST.get("mobile")
            if request.POST.get("qq"):
                request.user.qq = request.POST.get("qq")
            if request.POST.get("realname"):
                request.user.realname = request.POST.get("realname")
            request.user.save()
        except Exception as ex:
            ret_info = {"code": 200, "msg": "修改失败"}
        return render(request, "uc/uc_profile.html", {"ret_info": ret_info})


class Collect(LoginRequiredMixin,View):
    def get(self,request):
        from django.db import connection
        cursor = connection.cursor()
        sql = "SELECT house_houseinfo.id,house_houseinfo.type,house_houseinfo.info,house_houseinfo." \
              "location,house_houseinfo.photo,house_houseinfo.price,house_houseinfo.title FROM show_housecollection,Uc_user,house_houseinfo WHERE show_housecollection.user_id= %d and show_housecollection.status=1 and house_houseinfo.id=show_housecollection.house_id GROUP BY house_houseinfo.id" % request.user.id

        cursor.execute(sql)
        rows = cursor.fetchall()
        paginator = Paginator(rows, 12)
        page = request.GET.get('page')
        numlist = []
        if paginator.num_pages > 5:
            numlist = ['1', '2', '3', '4', '5']
        else:
            for i in range(1, paginator.num_pages + 1):
                numlist.append(str(i))
        try:
            contacts = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            contacts = paginator.page(1)
            page = 1
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            contacts = paginator.page(paginator.num_pages)
            page = paginator.num_pages

        # rows = cursor.fetchmany(2)  返回2条数据(3,4,5,6,7,...)
        kwag = {
            "houselist": contacts,
            "page" : page,
            'fivenum': numlist,
            'pagenum': paginator.num_pages,
        }

        return render(request,"uc/uc_collection.html",kwag)


class Order(LoginRequiredMixin,View):
    def get(self,request):
        from django.db import connection
        cursor = connection.cursor()
        sql = "SELECT house_houseinfo.id,house_houseinfo.type,house_houseinfo.info,house_houseinfo.location," \

LoveRoom/apps/Uc/templates/Uc/uc_base.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="container">
    <div class="row" style="height: 500px">
      <aside class="profile-info col-lg-3">
        <div class="panel" style="border-right: 1px solid #cccccc; height: 400px;margin: 20px">
          <div class="panel-body">
            <ul class="nav nav-pills nav-stacked" style="font-size: 18px;color: black">
            {% url 'uc:profile' as uc_profile %}
            {% url 'uc:change_passwd' as uc_change_passwd %}
            {% url 'uc:answer' as uc_answer %}
            {% url 'uc:collect' as uc_collect %}
            {% url 'uc:order' as uc_order %}
            {% url 'uc:myhouse' as uc_myhouse %}
            <li role="presentation" ><a href="{{ uc_profile }}" {% if request.path == '/uc/profile/' %}style="color: #0070ff"{% else %}style="color: #0a274e"{% endif %}><b>个人资料</b></a></li>
            <li role="presentation" ><a href="{{ uc_change_passwd }}" {% if request.path == '/uc/change_passwd/' %}style="color: #0070ff"{% else %}style="color: #0a274e"{% endif %}><b>修改密码</b></a></li>
    {#        <li role="presentation" class="{% if current_url == uc_answer %}active{% endif %}"><a href="{{ uc_answer }}">我的回答</a></li>#}
            <li role="presentation" ><a href="{{ uc_collect }}" {% if request.path == '/uc/collect/' %}style="color: #0070ff"{% else %}style="color: #0a274e"{% endif %}><b>我的收藏</b></a></li>
            <li role="presentation" ><a href="{{ uc_order }}" {% if request.path == '/uc/order/' %}style="color: #0070ff"{% else %}style="color: #0a274e"{% endif %}><b>我的订单</b></a></li>
            <li role="presentation" ><a href="{{ uc_myhouse }}" {% if request.path == '/uc/myhouse/' %}style="color: #0070ff"{% else %}style="color: #0a274e"{% endif %}><b>我的房源</b></a></li>
            </ul>
          </div>
        </div>
      </aside>
      <aside class="profile-info col-lg-9">
          <section>
              <div class="row">
                {% block uc_content %}
                  <div class="col-lg-12">
                      <div class="panel">
                          <div class="panel-body">
                              <div class="bio-chart">
                                  <input class="knob" data-width="100" data-height="100" data-displayPrevious=true  data-thickness=".2" value="35" data-fgColor="#e06b7d" data-bgColor="#e8e8e8">
                              </div>
                              <div class="bio-desk">
                                  <h4 class="red">Envato Website</h4>
                                  <p>Started : 15 July</p>
                                  <p>Deadline : 15 August</p>
                              </div>
                          </div>
                      </div>
                  </div>
                {% endblock %}
              </div>
          </section>

      </aside>
    </div>
</div>

{% endblock %}
{% block load_js %}
  <script src="{% static 'assets/jquery-knob/js/jquery.knob.js' %}"></script>
  <script>
      //knob
      $(".knob").knob();
  </script>
{% endblock %}

LoveRoom/apps/Uc/templates/Uc/uc_change_passwd.html
{% extends 'Uc/uc_base.html' %}
{% block uc_content %}
  <div class="col-lg-12">
      <div class="panel">
          <div class="panel-body">
              <b style="font-size: 15px">修改密码</b>
              <hr/>
              <div class="row col-md-7">
                    <form class="form-horizontal" role="form" method="post" href="{% url "uc:change_passwd" %}">
                         {% csrf_token %}
                          <div class="form-group">
                              <label for="inputPasswordOld" class="col-lg-3 control-label">旧密码</label>
                              <div class="col-lg-9">
                                  <input name="oldpassword" type="password" class="form-control" id="inputPasswordOld" placeholder="旧密码"  minlength="6" required>
                              </div>
                          </div>
                          <div class="form-group">
                              <label for="inputPasswordNew1" class="col-lg-3 control-label">新密码</label>
                              <div class="col-lg-9">
                                  <input name="newpassword1" type="password" class="form-control" id="inputPasswordNew1" placeholder="新密码"  minlength="6" required>
                              </div>
                          </div>
                          <div class="form-group">
                              <label for="inputPasswordNew1" class="col-lg-3 control-label">新密码</label>
                              <div class="col-lg-9">
                                  <input name="newpassword2" type="password" class="form-control" id="inputPasswordNew2" placeholder="请再输入一次新密码" minlength="6" required>
                              </div>
                          </div>
                          <div class="form-group">
                              <div class="col-lg-offset-3 col-lg-9">
                                  <button type="submit" class="btn btn-danger" id="change_passwd_btn"  style="color: white" disabled="disabled" >提交</button>
                              </div>
                          </div>
                     </form>
                  {{ ret_info }}
              </div>
          </div>
      </div>
  </div>

{% endblock %}
{% block load_js2 %}
<script>
var oldflag = false;
var newflag = false;
var newflag2 = false;
$("#inputPasswordOld").blur(function () {
    reg1 = /^.*[\d]+.*$/;
    reg2 = /^.*[A-Za-z]+.*$/;
    reg3 = /^.*[_@#%&^+-/*\/\\]+.*$/;//验证密码
    var Pval = $("#inputPasswordOld").val();
    if (Pval.length > 16 || Pval.length < 8) {
        alert("密码应为8-16个字符，区分大小写")
    } else if (!((reg1.test(Pval) && reg2.test(Pval)) || (reg1.test(Pval) && reg3.test(Pval)) || (reg2.test(Pval) && reg3.test(Pval)) )) {
        alert("需至少包含数字、字母和符号中的两种类型");
    }else{
        oldflag = true;
    }
    check();
});
$("#inputPasswordNew2").blur(function () {
    check()
});
$("#inputPasswordNew2").blur(function () {
    if ($("#inputPasswordNew1").val() != $("#inputPasswordNew2").val()) {
            $("#inputPasswordNew1").val('');
            $("#inputPasswordNew2").val('');
            alert("两次输入的新密码不一致！");
        }else{
            reg1 = /^.*[\d]+.*$/;
            reg2 = /^.*[A-Za-z]+.*$/;
            reg3 = /^.*[_@#%&^+-/*\/\\]+.*$/;//验证密码
            var Pval = $("#inputPasswordNew1").val();
            if (Pval.length > 16 || Pval.length < 8) {
                alert("密码应为8-16个字符，区分大小写")
            } else if (!((reg1.test(Pval) && reg2.test(Pval)) || (reg1.test(Pval) && reg3.test(Pval)) || (reg2.test(Pval) && reg3.test(Pval)) )) {
                alert("需至少包含数字、字母和符号中的两种类型");
            }else{
                newflag = true;
                newflag2 = true;
            }
            check();

    }
});
    function check() {
        if(oldflag && newflag && newflag2){
        $("#change_passwd_btn").removeAttr("disabled");
         }
    }

{% if msg %}
alert("{{ msg }}");
{% endif %}
</script>

{% endblock %}

LoveRoom/apps/Uc/templates/Uc/uc_collection.html
{% extends 'Uc/uc_base.html' %}
{% block uc_content %}
{% load myfilter %}
  <div class="col-lg-12">
      <div class="panel">
          <div class="panel-body">
              <h4>我的收藏</h4>
              <hr/>
                <div class="row">
				    <ul class="filter-list clearfix" style="width: 100%">
                    {% if houselist %}
                        {% for item in houselist %}
                        <li class="mix rent test col-md-4 col-sm-4 mrgb5x" data-price="5">
                            <a href="/show/{{ item.0 }}/?st={{ st }}&et={{ et }}">
                                <div class="property-box rent animated out" data-delay="0" data-animation="fadeInUp">
							<div class="appartment-img"><img src={{ item.4|get_img_url }} class="img-responsive" alt="#" style="width: 265px;height: 175px" />
								<div class="detail-btn"> <a href="#" class="rent" style="color:white;font-size: 12px">￥{{ item.5|price }}</a> </div>
							</div>
							<div class="property-text" style="height: 100px">
								<div class="appartment-name" >
                                    <a href="/show/{{ item.0 }}/?st={{ st }}&et={{ et }}"><h5 style="margin-bottom: 0px !important;font-size: 16px">{{ item.6|limit_title }}</h5></a>
                                    <a href="/show/{{ item.0 }}/?st={{ st }}&et={{ et }}"><p style="margin-bottom: 0px !important;height: 24px"><strong>{{ item.6|limit_title }}</strong></p></a>
                                    <p style="color: #9faab6;height: 15px"><span style="font-size: 5px">{{ item|housetype_sql }}  |</span><span style="font-size: 5px">可住{{ item.2|jsonvalue:"maxGuestNumber" }}人   |</span><span style="font-size: 5px">{{ item.3|jsonvalue:"districtName" }}</span><p>
									<div class="post-meta">

                                        <a style="color: #cf251f;" id="house_collect-{{ item.0 }}" class="like" ><i class="fa fa-heart"></i></a>



                                     </div>
                                    </div>
                                </div>
                            </div>
                            </a>
                        </li>
                        {% endfor %}
                    {% else %}
                        <h4>未收藏任何房源</h4>
                    {% endif %}

				</ul>
                <div class="numbering">
                        <ul class="pagination" id="pagination_cpb">

                            {% if houselist.has_previous %}
                            <li><a href="?page={{ houselist.previous_page_number }}">上一页</a></li>
                            {% endif %}
                            {% if page|contrast:'6'  %}
                                {% for i in fivenum %}
                                <li {% ifequal page i %}class="active"{% endifequal %}><a href="?page={{ i }}">{{ forloop.counter }}</a></li>
                                {% endfor %}
                                {% if pagenum|contrast:'6' %}
                                {% else %}
                                    <li ><a >···</a></li>
                                    <li ><a href="?page={{ pagenum}}">{{ pagenum }}</a></li>
                                {% endif %}
                            {% else %}
                                <li ><a href="?page=1">1</a></li>
                                <li ><a >···</a></li>

                                {% if page|add:'2' < pagenum %}
                                    <li ><a href="?page={{ page|add:'-2' }}">{{ page|add:'-2' }}</a></li>
                                    <li ><a href="?page={{ page|add:'-1' }}">{{ page|add:'-1' }}</a></li>
                                    <li class="active"><a href="?page={{ page }}">{{ page }}</a></li>
                                    <li ><a href="?page={{ page|add:'1' }}">{{ page|add:'1' }}</a></li>
                                    <li ><a href="?page={{ page|add:'2' }}">{{ page|add:'2' }}</a></li>
                                    <li><a>···</a></li>
                                    <li ><a href="?page={{ pagenum}}">{{ pagenum }}</a></li>
                                {% endif %}

                                {% ifequal page|add:'2'  pagenum  %}
                                    <li ><a href="?page={{ page|add:'-2' }}">{{ page|add:'-2' }}</a></li>
                                    <li ><a href="?page={{ page|add:'-1' }}">{{ page|add:'-1' }}</a></li>
                                    <li class="active"><a href="?page={{ page }}">{{ page }}</a></li>
                                    <li ><a href="?page={{ page|add:'1' }}">{{ page|add:'1' }}</a></li>
                                    <li ><a href="?page={{ page|add:'2' }}">{{ page|add:'2' }}</a></li>
                                {% endifequal %}
                                {% ifequal page|add:'1'  pagenum  %}
                                    <li ><a href="?page={{ page|add:'-3' }}">{{ page|add:'-3' }}</a></li>
                                    <li ><a href="?page={{ page|add:'-2' }}">{{ page|add:'-2' }}</a></li>
                                    <li ><a href="?page={{ page|add:'-1' }}">{{ page|add:'-1' }}</a></li>
                                    <li class="active"><a href="?page={{ page }}">{{ page }}</a></li>
                                    <li ><a href="?page={{ page|add:'1' }}">{{ page|add:'1' }}</a></li>
                                {% endifequal %}
                                {% ifequal page|add:'0'  pagenum  %}
                                    <li ><a href="?page={{ page|add:'-4' }}">{{ page|add:'-4' }}</a></li>
                                    <li ><a href="?page={{ page|add:'-3' }}">{{ page|add:'-3' }}</a></li>
                                    <li ><a href="?page={{ page|add:'-2' }}">{{ page|add:'-2' }}</a></li>
                                    <li ><a href="?page={{ page|add:'-1' }}">{{ page|add:'-1' }}</a></li>
                                    <li class="active"><a href="?page={{ page }}">{{ page }}</a></li>
                                {% endifequal %}

                            {% endif %}


                            {% if houselist.has_next %}
                            <li><a href="?page={{ houselist.next_page_number }}">下一页</a></li>
                            {% endif %}


					    </ul>
				    </div>
                </div>

          </div>
      </div>
  </div>



{% endblock %}